branches:
  only:
    - master
    - dev
    - /^v.*$/
    - /^release/*$/
    - /^hotfix/*$/
    - travis-debug
    - fix/travis-build

os: osx
osx_image: xcode11.2
language: node_js
node_js:
  - 12

script:
  - |
    npm run icon-gen &&
    npm run release -- -mwl -c.snap.publish=github
