branches:
  only:
    - master
    - dev
    - /^release\/.*$/
    - /^hotfix\/.*$/

os: osx
osx_image: xcode11.2
language: node_js
node_js:
  - 12

jobs:
  include:
    - stage: test
      script:
        - >
          npm test
          && npm run flow
    - stage: deploy
      script:
        - |
          npm run icon-gen &&
          npm run release -- -mwl -c.snap.publish=github

stages:
  - name: test
  - name: deploy
    if: branch =~ /^(master|release\/).*$/
